name: Verify Copyright Headers

on:
  workflow_call:
    inputs:
      config:
        description: 'Toml config for the copyright tool'
        required: true
        type: string
      directory:
        description: 'Root directory to check recursively'
        required: true
        type: string

jobs:
  verify-copyright:
    name: Verify Copyright Headers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout calling repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout toolbox repository
        uses: actions/checkout@v6
        with:
          repository: SlyFryFrog/toolbox
          path: toolbox

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Verify copyright headers
        run: |
          python3 toolbox/scripts/copyright/copyright.py \
            --config "${{ inputs.config }}" \
           	--directory "${{ inputs.directory }}" \
            --override

      - name: Show diff if violations found
        if: failure()
        run: |
          echo "::error::Copyright header violations found"
          python3 toolbox/scripts/copyright/copyright.py \
            --config "${{ inputs.config }}" \
            --directory "${{ inputs.directory }}" \
            --fix \
            --override
          git diff
          exit 1
